oadp-1.0: Fix CVE-2023-39325
konveyor/openshift-velero-plugin pull request #209
Opened 2023-10-16 18:58 UTC by weshayutin

2023-10-16 19:52 UTC, kaovilai requested changes
Please add `-buildvcs=false` to Dockerfile
[like so](https://github.com/openshift/openshift-velero-plugin/pull/201/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R22)

2023-10-16 20:07 UTC, mateusoliveira43 commented on Dockerfile
> +RUN go build -buildcvs=false -installsuffix "static" -tags "$BUILDTAGS" -o _output/$BIN ./$BIN
typo buildcvs -> buildvcs

2023-10-16 20:28 UTC, kaovilai commented on Dockerfile
> +RUN go build -buildcvs=false -installsuffix "static" -tags "$BUILDTAGS" -o _output/$BIN ./$BIN
take your cvs pill @weshayutin

2023-10-16 20:34 UTC, weshayutin commented on Dockerfile
> +RUN go build -buildcvs=false -installsuffix "static" -tags "$BUILDTAGS" -o _output/$BIN ./$BIN
![PXL_20231016_203251374](https://github.com/openshift/openshift-velero-plugin/assets/138787/04b41d7d-12a5-44b1-b80c-578037272273)

2023-10-17 14:10 UTC, kaovilai approved these changes
/lgtm

2023-10-17 14:36 UTC, merged